defaultEntryPoints = ["https"]

[entryPoints]
[entryPoints.https]
address = ":443"

[providers.docker]
exposedbydefault = false

[providers.file]
directory = "/dynamic/https"

[docker]
domain = "sca-agent"
network = "SCA"
watch = true

# [accessLog]
