server:
  port: 80

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd-HH:mm:ss}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{15}){cyan}  [%clr(%X{cx}){blue}] %clr(:){faint} %replace(%m){'([\\|])','\\$1'}%n%wEx"

cx-flow:
  bug-tracker: None
  enabled-vulnerability-scanners:
    - sca
  branches:
    - develop
    - master
    - security
    - main
  filter-severity:
    - High
    - Medium

sca:
  appUrl: ${AGENT_INTERNAL_URL}
  apiUrl: ${AGENT_INTERNAL_URL}
  accessControlUrl: ${AGENT_INTERNAL_URL}
  tenant: ${SCA_TENANT}
  username: ${SCA_USERNAME}
  password: ${SCA_PASSWORD}

github:
  webhook-token: ${WEBHOOK_SECRET}
  token: ${WEBHOOK_TOKEN}
  url: https://github.com
  api-url: https://api.github.com/repos/
  false-positive-label: false-positive
  block-merge: true
  config-as-code:
  error-merge: true
  cx-summary: false
  flow-summary: true
