server:
  port: 80

cx-flow:
  bug-tracker: None
  enabled-vulnerability-scanners:
    - sca
  branches:
    - develop
    - master
    - security
    - main
  filter-severity:
    - High
    - Medium

sca:
  appUrl: ${AGENT_INTERNAL_URL}
  apiUrl: ${AGENT_INTERNAL_URL}
  accessControlUrl: ${AGENT_INTERNAL_URL}
  tenant: ${SCA_TENANT}
  username: ${SCA_USERNAME}
  password: ${SCA_PASSWORD}

github:
  webhook-token: ${WEBHOOK_SECRET}
  token: ${WEBHOOK_TOKEN}
  url: https://github.com
  api-url: https://api.github.com/repos/
  false-positive-label: false-positive
  block-merge: true
  config-as-code:
  error-merge: true
  cx-summary: false
  flow-summary: true
