http:
  routers:
    risk-management-router:
      rule: PathPrefix(`/risk-management`)
      entryPoints:
        - http
      middlewares:
        - hostHeader
      service: sca-cloud

    remediation-router:
      rule: PathPrefix(`/remediation`)
      entryPoints:
        - http
      middlewares:
        - hostHeader
      service: sca-cloud

    notification-router:
      rule: PathPrefix(`/notification`)
      entryPoints:
        - http
      middlewares:
        - hostHeader
      service: sca-cloud

    packages-router:
      rule: PathPrefix(`/packages`)
      entryPoints:
        - http
      middlewares:
        - hostHeader
      service: sca-cloud

    settings-router:
      rule: PathPrefix(`/settings`)
      entryPoints:
        - http
      middlewares:
        - hostHeader
      service: sca-cloud

    policy-management-router:
      rule: PathPrefix(`/policy-management`)
      entryPoints:
        - http
      middlewares:
        - hostHeader
      service: sca-cloud

    access-control-router:
      rule: PathPrefix(`/identity`)
      entryPoints:
        - http
      middlewares:
        - accessControlHostHeader
      service: access-control

  middlewares:
    hostHeader:
      headers:
        customRequestHeaders:
          Host: {{env "SCA_API_HOST"}}
    accessControlHostHeader:
      headers:
        customRequestHeaders:
          Host: {{env "ACCESS_CONTROL_HOST"}}

  services:
    sca-cloud:
      loadBalancer:
        servers:
          - url: {{env "SCA_API_PROTOCOL"}}://{{env "SCA_API_HOST"}}/
    access-control:
      loadBalancer:
        servers:
          - url: {{env "ACCESS_CONTROL_PROTOCOL"}}://{{env "ACCESS_CONTROL_HOST"}}/
